### ISSUE TITLE
Disconnect TravisCI and run linters in Gitlab

### ISSUE THREAD

**Issue by jkevingutierrez** [neon-jungle/wagtail-videos#69]
In https://github.com/neon-jungle/wagtailvideos/commit/ac584ed5ddbbd8ff2ef2e8224d852ac6104ae199 Travis was removed, and Gitlab was added.

Even though, TravisCI is still trying to run when someone creates a PR.

![image](https://user-images.githubusercontent.com/6220055/108071344-a04d5e00-7033-11eb-895e-27f62691934f.png)

It would also be good to run linters (flake8 and isort) in the new Gitlab pipeline. Similar to https://github.com/neon-jungle/wagtailvideos/blob/2.8.2/tox.ini#L42

**Comment by seb-b** [comment]
Unfortunately I've lost access to the travis account, working on getting it back. Can definitely add the linters to gitlab, there's an an example from another project [here](https://github.com/neon-jungle/wagtail-birdsong/blob/master/.gitlab-ci.yml)

**Comment by seb-b** [comment]
gitlab linting has been added
